/* CONFIG PROPERTIES */
export const APP_PORT = 'APP_PORT';
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const DATABASE_NAME = 'DATABASE_NAME';

/* PROVIDERS */
export const MONGO_CLIENT = 'MONGO_CLIENT';
