/* CONFIG PROPERTIES */
export const APP_PORT = 'APP_PORT';
export const AUTH_JWT_SECRET_KEY = 'AUTH_JWT_SECRET_KEY';
export const AUTH_JWT_EXP_TIME = 'AUTH_JWT_EXP_TIME';
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const DATABASE_NAME = 'DATABASE_NAME';

/* PROVIDERS */
export const MONGO_CLIENT = 'MONGO_CLIENT';

/* MONGODB CONSTANTS */
export const MONGO_COLLECTION_USERS = 'users';
